image: Ubuntu2004

stack: jdk 11

branches:
  only:
    - main

build: off

install:

  - java -jar ./artifacts/app-order.jar &
  - chmod +x gradlew
  - ./gradlew test --info -Selenide.headless=true

build_script:
  - ./gradlew test --info